routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    abort,
    send_from_directory)

from models.board import Board
from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import *
from utils import log


main = Blueprint('index', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.find_all(board_id=board_id)
    bs = Board.all()
    return render_template("visit/index.html", ms=ms, bs=bs, bid=board_id,)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    board_id = int(request.args.get('board_id', -1))
    u = m.user()
    return render_template("visit/detail.html", topic=m, bid=board_id, user=u)


@main.route('/author')
def author_detail():
    user_id = int(request.args.get('id'))
    u = User.find(user_id)
    ts = Topic.topics_reverse_order(user_id)
    r = Reply.find_all(user_id=user_id)
    rt = remove_repeat(r)

    if u is None:
        abort(404)
    else:
        return render_template('visit/author.html', user=u, topic=ts, rt=rt)


@main.route("/user_login")
def user_login():
    return render_template("login.html")


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    notice = '注册成功'
    if u is None:
        notice = '用户名输入有误或已存在'
    return render_template("login.html", n1=notice)


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)

    if u is None:
        # 转到 topic.index 页面
        notice = '用户名或密码不正确'
        return render_template("login.html", n2=notice)
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route('/user/<username>')
def user_detail(username):
    u = User.find_by(username=username)
    ts = Topic.topics_reverse_order(u.id)
    r = Reply.find_all(user_id=u.id)
    rt = remove_repeat(r)
    cu = current_user()

    if u is None:
        abort(404)
    else:
        return render_template('user/user_detail.html', user=u, topic=ts, rt=rt, current_user=cu)


@main.route('/image/add', methods=['POST'])
def add_img():
    u = current_user()
    file = request.files['avatar']
    suffix = file.filename.split('.')[-1]
    if valid_suffix(suffix):
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        file.save(os.path.join('user_image', filename))
        u.user_image = '/uploads/' + filename
        u.save()
    return redirect(url_for('.user_detail', username=u.username))


@main.route('/uploads/<filename>')
def uploads(filename):
    return send_from_directory('user_image', filename)


@main.route('/image/<filename>')
def image(filename):
    return send_from_directory('image', filename)


@main.route("/setting")
def setting():
    u = current_user()
    return render_template('user/setting.html', user=u, user_id=u.id)


@main.route("/setting_user_sig", methods=["POST"])
def setting_user_sig():
    u = current_user()
    form = request.form
    u.signature = form.get('signature')
    u.username = form.get('username')
    u.save()
    return redirect(url_for('.setting'))


@main.route("/changing_password", methods=["POST"])
def changing_password():

    u = current_user()
    form = request.form
    new_password = form.get('new_pass', u.password)
    old_password = form.get('old_pass')

    if u is not None and u.password == u.salted_password(old_password):
        u.password = u.salted_password(new_password)
    u.save()
    return redirect(url_for('.setting', old_pass=old_password, new_pass=new_password))


@main.route('/attack')
def attack():
    # xss 攻击的后台
    cookie = request.args.get('cookie')
    log('cookie', cookie)

templates/visit/author.html
{% extends "visit/base.html" %}
{% block main %}
    <div id="main">
        <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">作者信息</span >
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="{{ url_for('index.author_detail', id=user.id) }}">
                            <img src="{{ user.user_image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name"><a class="dark" href="{{ url_for('index.author_detail', id=user.id) }}">{{ user.username }}</a></span>
                        <div class="board clearfix">
                            <div class="floor">
                            </div>
                        </div>
                        <span class="signature">
                            {{ user.signature }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>友情站点</span>
            </div>
            <div class='inner'>
                <ol class="friendship-community">
                    <li>
                        <a href="https://www.google.com/" target="_blank">
                            <img src="/static/image/google.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://github.com/" target="_blank">
                            <img src="/static/image/github1.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://www.zhihu.com/" target="_blank">
                            <img src="/static/image/zhihu.png">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://stackoverflow.com/" target="_blank">
                            <img src="/static/image/stackoverflow1.jpg">
                        </a>
                    </li>
                </ol>
            </div>
        </div>
    </div>

        <div id="content">
            <div class="panel">
                <div class="header">
                    <ul class="breadcrumb">
                        <li>
                            <a href="">{{ user.username }}的主页</a>
                        </li>
                    </ul>
                </div>
                <div class="inner userinfo">
                    <div class="user_big_avatar">
                        <img src="{{ user.user_image }}" title="{{ user.username }}">
                    </div>
                    <a class="dark">{{ user.username }}</a>
                    <p class="col_fad" id="{{ user.created_time }}"></p>
                </div>
            </div>

            <div class="panel">
                <div class="header">
                    <span class="col_fade">最近创建的话题</span>
                </div>
                {% for t in topic %}
                    <div class="cell">
                        <a class="user_avatar pull-left" href="{{ url_for('index.author_detail', id=user.id) }}">
                            <img src="{{ user.user_image }}" title="{{ user.username }}">
                        </a>

                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">
                                {{ t.replies() | count }}
                            </span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title="点击数">
                                {{ t.views }}
                            </span>
                        </span>

                        <a class="last_time pull-right" href="{{ url_for('index.author_detail', id=user.id) }}">
                            <img class="user_small_avatar" src="{{ user.user_image }}">
                            <span class="last_active_time" id="{{ t.created_time }}"> </span>
                        </a>

                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('index.detail', id=t.id) }}" title="{{ t.title }}">
                                {{ t.title }}
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="panel">
                <div class="header">
                    <span class="col_fade">最近参与的话题</span>
                </div>
                {% for t in rt %}
                    <div class="cell">
                        <a class="user_avatar pull-left" href="{{ url_for('index.author_detail', id=user.id) }}">
                            <img src="{{ user.user_image }}" title="{{ user.username }}">
                        </a>
                        <span class="reply_count pull-left">
                            <span class="count_of_replies" title="回复数">
                                {{ t.replies() | count }}
                            </span>
                            <span class="count_seperator">/</span>
                            <span class="count_of_visits" title="点击数">
                                {{ t.views }}
                            </span>
                        </span>

                        <a class="last_time pull-right" href="{{ url_for('index.author_detail', id=t.user().id) }}">
                            <img class="user_small_avatar" src="{{ t.user().user_image }}">
                            <span class="last_active_time" id="{{ t.created_time }}"> </span>
                        </a>
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('index.detail', id=t.id) }}" title="{{ t.title }}">
                                {{ t.title }}
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script>
    var log = function() {
        console.log.apply(console, arguments)
    }

    var e = function(sel) {
        return document.querySelector(sel)
    }

    var es = function(sel) {
        return document.querySelectorAll(sel)
    }

    var registerTime = function() {
        var ctime = e('.col_fad')
        var now = Math.floor(new Date() / 1000)
        var delta = Math.floor(((now - Number(ctime.id))/ 3600))
        var day = Math.floor(delta/24)
        var s = '注册时间 ' + day + '天前'
        ctime.innerText = s
    }

    var creatTime = function() {
        var ctimes = es('.last_active_time')
        for(var i = 0; i < ctimes.length; i++) {
            var now = Math.floor(new Date() / 1000)
            var delta = Math.floor(((now - Number(ctimes[i].id))/ 3600))
            var s = delta + '小时前'
            ctimes[i].innerText = s
        }
    }

    var __main = function() {
        console.log('running')
        registerTime()
        creatTime()
    }

    __main()

    </script>
{% endblock %}

templates/visit/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!-- style -->
        <link rel="stylesheet" href="/static/css/index.min.9d1ebdbb.min.css">
        <!-- scripts -->
        <script async="" src="/static/js/analytics.js"></script>
        <script async="" src="/static/js/index.min.aeb155e1.min.js"></script>
        <script src="https://cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
        <link rel="Shortcut Icon" href="/static/image/favicon.ico"/>
        <title>AL社区</title>
    </head>
    <body>
        <div class='navbar'>
            <div class='navbar-inner'>
                <div class='container'>
                    <a class='brand' href='/'>
                        <img src="/static/image/123.png">
                    </a>
                    <form id='search_form' class='navbar-search' action="/search">
                        <input type='text' id='q' name='q' class='search-query span3' value=''/>
                    </form>
                    <ul class='nav pull-right'>
                        <li>
                            <a href='/'>首页</a>
                        </li>
                        <li>
                            <a href='/user_login'>注册</a>
                        </li>
                        <li>
                            <a href='/user_login'>登录</a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>
        {% block main %}{% endblock %}
        <div id="backtotop" style="display: none; top: 358px; right: 0px;">回到顶部</div>
        <div id="sidebar-mask"></div>
        <div id='footer'>
            <div id='footer_main'>
                <div class="links">
                    <img src="/static/image/githubIcon1.jpg">
                        |
                    <a class='dark' href='https://github.com/QAQAL/per-forum'>源码地址</a>
                </div>
                <div class='col_fade'>
                    <p>
                        <span style="color:#66A800;font-weight:bold">AL社区</span>
                        个人搬砖社区，专注搬砖节奏研究。
                    </p>
                </div>
            </div>
        </div>
    </body>
</html>

templates/visit/detail.html
{% extends "visit/base.html" %}
{% block main %}
<div id="main">
    <div id="sidebar">

        <div class="panel">
            <div class="header">
                <span class="col_fade">作者信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="{{ url_for('index.author_detail', id=topic.user().id) }}">
                            <img src="{{ user.user_image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name">
                            <a class="dark" href="{{ url_for('index.author_detail', id=topic.user().id) }}">
                                {{ user.username }}
                            </a>
                        </span>
                        <div class="board clearfix"><div class="floor"></div></div>
                        <span class="signature">
                            {{ user.signature }}
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>友情站点</span>
            </div>
            <div class='inner'>
                <ol class="friendship-community">
                    <li>
                        <a href="https://www.google.com/" target="_blank">
                            <img src="/static/image/google.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://github.com/" target="_blank">
                            <img src="/static/image/github1.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://www.zhihu.com/" target="_blank">
                            <img src="/static/image/zhihu.png">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://stackoverflow.com/" target="_blank">
                            <img src="/static/image/stackoverflow1.jpg">
                        </a>
                    </li>
                </ol>
            </div>
        </div>
    </div>

    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
                <span class="topic_full_title">
			        {{ topic.title }}
      	        </span>
                <div class="changes">
                    <span>发布于
                        <span class="col" id="{{ topic.created_time }}"></span>
                        天前</span>
                    <span>
                        作者
                        <a href="{{ url_for('index.author_detail', id=topic.user().id) }}">
                            {{ topic.user().username }}
                        </a>
        	        </span>
                    <span>
          	            {{ topic.views }} 次浏览
        	        </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>

        <div class="panel">
            <div class='header'>
                <span class='col_fade'>
                    <!-- 过滤器 -->
                    {{ topic.replies() | count }} 回复
                </span>
            </div>
            {% for r in topic.replies() %}
                <div class='cell reply_area reply_item'>
                    <div class='author_content'>
                        <a href="{{ url_for('index.author_detail', id=r.user().id) }}" class="user_avatar">
                            <img src="/uploads/default.png" title="{{ r.user().username }}"/>
                        </a>
                        <div class='user_info'>
                            <a class='dark reply_author'>
                                {{ r.user().username }}
                            </a>
                            <a class="reply_time">
                                {{ loop.index }}楼 •
                                <span class="last_active_time" id="{{ r.created_time }}"></span>
                            </a>
                        </div>
                    </div>
                    <div class='reply_content from-leiwei1991'>
                        <div class="markdown-text">
                            {{ r.content }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<script>
    var log = function() {
        console.log.apply(console, arguments)
    }

    var e = function(sel) {
        return document.querySelector(sel)
    }

    var es = function(sel) {
        return document.querySelectorAll(sel)
    }

    var registerTime = function() {
        var ctime = e('.col')
        var now = Math.floor(new Date() / 1000)
        var delta = Math.floor(((now - Number(ctime.id))/ 3600))
        var day = Math.floor(delta/24)
        var s = day
        ctime.innerText = s
    }

    var creatTime = function() {
        var ctimes = es('.last_active_time')
        for(var i = 0; i < ctimes.length; i++) {
            var now = Math.floor(new Date() / 1000)
            var delta = Math.floor(((now - Number(ctimes[i].id))/ 3600))
            var s = delta + '小时前'
            ctimes[i].innerText = s
        }
    }

    var __main = function() {
        console.log('running')
        registerTime()
        creatTime()
    }

    __main()
</script>
{% endblock %}

templates/visit/index.html
{% extends "visit/base.html" %}
{% block main %}
<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="inner">
                <a href="/user_login" class="create_topic_btn">
                    <span class="span-info">注册登录</span>
                </a>
            </div>
        </div>

       <div class='panel'>
            <div class='header'>
                <span class='col_fade'>友情站点</span>
            </div>
            <div class='inner'>
                <ol class="friendship-community">
                    <li>
                        <a href="https://www.google.com/" target="_blank">
                            <img src="/static/image/google.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://github.com/" target="_blank">
                            <img src="/static/image/github1.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://www.zhihu.com/" target="_blank">
                            <img src="/static/image/zhihu.png">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://stackoverflow.com/" target="_blank">
                            <img src="/static/image/stackoverflow1.jpg">
                        </a>
                    </li>
                </ol>
            </div>
        </div>
    </div>

    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/" class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/?board_id={{ b.id }}" class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="user_avatar" href="{{ url_for('index.author_detail', id=t.user().id) }}">
                                <img src="{{ t.user().user_image }}" title="{{ t.user().username }}">
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            <a class="topic_title" href="{{ url_for('index.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}