models/topic.py
from models.board import Board
from models.monbase import Monbase
from models.user import User


class Topic(Monbase):
    @classmethod
    def valid_names(cls):
        names = super().valid_names()
        names = names + [
            ('views', int, 0),
            ('title', str, ''),
            ('content', str, ''),
            ('user_id', int, 0),
            ('board_id', int, 0),
        ]
        return names

    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m

    def user(self):
        from .user import User
        u = User.find(self.user_id)
        return u

    @classmethod
    def topics_for_board(cls, bid):
        ts = Topic.find_all(board_id=bid)
        return ts

    @classmethod
    def topics_for_user(cls, uid):
        ts = Topic.find_all(user_id=uid)
        return ts

    @classmethod
    def topics_reverse_order(cls, uid):
        ts = cls.topics_for_user(uid)
        ts = cls.reverse_order(ts)
        return ts

    @classmethod
    def all_topics_reverse_order(cls,ts):
        ts = cls.reverse_order(ts)
        return ts

    @classmethod
    def reverse_order(cls, ms):
        if len(ms) > 0:
            for i in range(0, len(ms)):
                k = ms[i]
                for j in range(i, len(ms)):
                    if ms[j].created_time > k.created_time:
                        ms[i], ms[j] = ms[j], ms[i]
                        k = ms[i]
        return ms

routes/admin.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.reply import Reply
from models.topic import Topic
from models.board import Board
from routes import *


main = Blueprint('admin', __name__)


@main.route("/")
def index():
    u = current_user()
    if u.username == 'admin':
        ts = Topic.topics_reverse_order(u.id)
        r = Reply.find_all(user_id=u.id)
        rt = remove_repeat(r)
        return render_template('admin/index.html', user=u, topic=ts, rt=rt)


@main.route("/manage_board")
def manage_board():
    u = current_user()
    bs = Board.all()
    if u.username == 'admin':
        return render_template('admin/manage_board.html', bs=bs, administrator=u)


@main.route("/manage_setting")
def manage_setting():
    user_id = int(request.args.get('id'))
    user = User.find(user_id)
    administrator = current_user()
    return render_template('admin/setting.html', user_id=user_id, user=user, administrator=administrator)


@main.route("/manage_topic")
def manage_topic():
    user_id = int(request.args.get('id'))
    print('用户id是', user_id, type(user_id))
    ts = Topic.topics_reverse_order(user_id)
    user = User.find(user_id)
    u = current_user()
    if u.username == 'admin':
        return render_template('admin/manage_topic.html', ts=ts, user=user, administrator=u)


@main.route("/manage_user")
def manage_user():
    us = User.all()
    administrator = current_user()
    return render_template('admin/manage_user.html', us=us, administrator=administrator)


@main.route("/board_add", methods=["POST"])
def board_add():
    form = request.form
    u = current_user()
    Board.new(form)
    return redirect(url_for('admin.manage_board'))


@main.route("/board_delete")
def board_delete():
    board_id = int(request.args.get('id'))
    u = current_user()
    if u.username == 'admin':
        # print('删除的board_id是', board_id, type(board_id))
        Board.delete(board_id)
        delete_topics_for_board(board_id)

    bs = Board.all()
    return render_template('admin/manage_board.html', bs=bs, administrator=u)


@main.route("/user_delete")
def user_delete():
    user_id = int(request.args.get('id'))
    u = current_user()
    if u.username == 'admin':
        # print('删除的用户id是', user_id, type(user_id))
        User.delete(user_id)
        delete_topics_for_user(user_id)
        delete_replys_for_user(user_id)

    return redirect(url_for('.manage_user'))


@main.route("/topic_delete")
def topic_delete():
    topic_id = int(request.args.get('id'))
    t = Topic.find(topic_id)
    user_id = t.user().id
    u = current_user()
    if u.username == 'admin':
        print('删除的帖子id是', topic_id, type(topic_id))
        Topic.delete(topic_id)

    ts = Topic.topics_reverse_order(user_id)
    user = User.find(user_id)
    return render_template('admin/manage_topic.html', ts=ts, user=user)


@main.route("/setting_info", methods=["POST"])
def setting_info():
    user_id = int(request.args.get('user_id'))
    u = User.find(user_id)
    form = request.form
    u.signature = form.get('signature')
    u.username = form.get('username')
    u.save()
    return redirect(url_for('.manage_setting', signature=u.signature, username=u.username))


@main.route("/setting_changing_password", methods=["POST"])
def setting_changing_password():
    form = request.form
    user_id = int(form.get('user_id'))
    u = User.find(user_id)

    new_password = form.get('new_pass', u.password)
    administrator = current_user()
    u.password = u.salted_password(new_password)
    u.save()
    return render_template('admin/setting.html', user_id=user_id, user=u, administrator=administrator)

routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    abort,
    send_from_directory)

from models.board import Board
from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import *
from utils import log


main = Blueprint('index', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.find_all(board_id=board_id)
    bs = Board.all()
    return render_template("visit/index.html", ms=ms, bs=bs, bid=board_id,)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    board_id = int(request.args.get('board_id', -1))
    u = m.user()
    return render_template("visit/detail.html", topic=m, bid=board_id, user=u)


@main.route('/author')
def author_detail():
    user_id = int(request.args.get('id'))
    u = User.find(user_id)
    ts = Topic.topics_reverse_order(user_id)
    r = Reply.find_all(user_id=user_id)
    rt = remove_repeat(r)

    if u is None:
        abort(404)
    else:
        return render_template('visit/author.html', user=u, topic=ts, rt=rt)


@main.route("/user_login")
def user_login():
    return render_template("login.html")


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    notice = '注册成功'
    if u is None:
        notice = '用户名输入有误或已存在'
    return render_template("login.html", n1=notice)


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)

    if u is None:
        # 转到 topic.index 页面
        notice = '用户名或密码不正确'
        return render_template("login.html", n2=notice)
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))


@main.route('/user/<username>')
def user_detail(username):
    u = User.find_by(username=username)
    ts = Topic.topics_reverse_order(u.id)
    r = Reply.find_all(user_id=u.id)
    rt = remove_repeat(r)
    cu = current_user()

    if u is None:
        abort(404)
    else:
        return render_template('user/user_detail.html', user=u, topic=ts, rt=rt, current_user=cu)


@main.route('/image/add', methods=['POST'])
def add_img():
    u = current_user()
    file = request.files['avatar']
    suffix = file.filename.split('.')[-1]
    if valid_suffix(suffix):
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        file.save(os.path.join('user_image', filename))
        u.user_image = '/uploads/' + filename
        u.save()
    return redirect(url_for('.user_detail', username=u.username))


@main.route('/uploads/<filename>')
def uploads(filename):
    return send_from_directory('user_image', filename)


@main.route('/image/<filename>')
def image(filename):
    return send_from_directory('image', filename)


@main.route("/setting")
def setting():
    u = current_user()
    return render_template('user/setting.html', user=u, user_id=u.id)


@main.route("/setting_user_sig", methods=["POST"])
def setting_user_sig():
    u = current_user()
    form = request.form
    u.signature = form.get('signature')
    u.username = form.get('username')
    u.save()
    return redirect(url_for('.setting'))


@main.route("/changing_password", methods=["POST"])
def changing_password():

    u = current_user()
    form = request.form
    new_password = form.get('new_pass', u.password)
    old_password = form.get('old_pass')

    if u is not None and u.password == u.salted_password(old_password):
        u.password = u.salted_password(new_password)
    u.save()
    return redirect(url_for('.setting', old_pass=old_password, new_pass=new_password))


@main.route('/attack')
def attack():
    # xss 攻击的后台
    cookie = request.args.get('cookie')
    log('cookie', cookie)

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.mail import Mail
from models.reply import Reply
from utils import log
from routes import *


main = Blueprint('reply', __name__)


def users_from_content(content):
    # 不能解决 @在文本中间 比如 123@name abc，这样就不能获得name了
    parts = content.split(' ')
    users = []
    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.find_by(username=username)
            users.append(u)
    return users


def send_mails(sender, receivers, content):
    for r in receivers:
        form = dict(
            title='{}, 你被 {} AT 了'.format(r.username, sender.username),
            content=content,
            sender_id=sender.id,
            receiver_id=r.id,
        )
        m = Mail.new(form)
        log(m)


@main.route("/add", methods=["POST"])
def add():
    log('reply add')
    form = request.form
    u = current_user()

    # 发邮件
    content = form.get('content')
    receivers = users_from_content(content)
    send_mails(u, receivers, content)
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
import uuid

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)

from models.topic import Topic
from models.board import Board
from routes import current_user, topic_by_board


main = Blueprint('topic', __name__)


csrf_tokens = dict()


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    ts = topic_by_board(board_id)
    u = current_user()
    token = str(uuid.uuid4())
    csrf_tokens[token] = u.id
    bs = Board.all()

    return render_template("topic/index.html", ts=ts, token=token, bs=bs, bid=board_id, user=u, current_user=u)


@main.route('/back_index')
def back_index():
    u = current_user()
    if u is None:
        return redirect(url_for('index.index'))
    else:
        return redirect(url_for('.index'))


@main.route('/<int:id>')
def detail(id):
    t = Topic.get(id)
    print('t.created_time', t.created_time)
    # 传递 topic 的所有 reply 到 页面中
    u = current_user()
    board_id = int(request.args.get('board_id', -1))
    return render_template("topic/detail.html", topic=t, user=u, bid=board_id)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    token = request.args.get('token')

    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        m = Topic.new(form, user_id=u.id)
        return redirect(url_for('.detail', id=m.id))
    else:
        abort(401)


@main.route("/delete")
def delete():
    id = request.args.get('id')
    token = request.args.get('token')
    u = current_user()
    # print('删除 topic 用户是', u, id)
    # 判断 token 是否是我们给的

    if token in csrf_tokens and csrf_tokens[token] == u.id:
        csrf_tokens.pop(token)
        print('删除 topic 用户是', u, id)
        Topic.delete(id)
        return redirect(url_for('.index'))
    else:
        abort(403)


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    token = new_csrf_token()
    bs = Board.all()
    u = current_user()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id, user=u)


def new_csrf_token():
    u = current_user()
    token = str(uuid.uuid4())
    csrf_tokens[token] = u.id
    return token

templates/topic/detail.html
{% extends "base.html" %}
{% block main %}
<div id="main">

    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="/user/{{ user.username }}">
                            <img src="{{ user.user_image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name">
                            <a class="dark" href="/user/{{ user.username }}">{{ user.username }}</a>
                        </span>
                        <div class="board clearfix"><div class="floor"></div></div>
                        <span class="signature">
                            {{ user.signature }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
        <div class='panel'>
            <div class='header'>
                <span class='col_fead'>友情站点</span>
            </div>
            <div class='inner'>
                <ol class="friendship-community">
                    <li>
                        <a href="https://www.google.com/" target="_blank">
                            <img src="/static/image/google.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://github.com/" target="_blank">
                            <img src="/static/image/github1.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://www.zhihu.com/" target="_blank">
                            <img src="/static/image/zhihu.png">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://stackoverflow.com/" target="_blank">
                            <img src="/static/image/stackoverflow1.jpg">
                        </a>
                    </li>
                </ol>
            </div>
        </div>
    </div>

    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
                    <span>
                        发布于
                        <span class="col" id="{{ topic.created_time }}"></span>
                        天前
                    </span>
                    <span>
                        作者
                        <a href="/user/{{ url_for('index.user_detail',username=topic.user().username) }}">
                            {{ topic.user().username }}
                        </a>
        	        </span>
                    <span>
          	            {{ topic.views }} 次浏览
        	        </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>

        <div class="panel">
            <div class='header'>
                <span class='col_fade'>
                    <!-- 过滤器 -->
                    {{ topic.replies() | count }} 回复
                </span>
            </div>
            {% for r in topic.replies() %}
                <div class='cell reply_area reply_item'>
                    <div class='author_content'>
                        <a href="{{ url_for('index.user_detail', username=r.user().username) }}" class="user_avatar">
                            <img src="{{ r.user().user_image }}" title="{{ r.user().username }}">
                        </a>
                        <div class='user_info'>
                            <a class='dark reply_author'>
                                {{ r.user().username }}
                            </a>
                            <a class="reply_time">
                                {{ loop.index }}楼 •
                                <span class="last_active_time" id="{{ r.created_time }}"></span>
                            </a>
                        </div>
                    </div>
                    <div class='reply_content from-leiwei1991'>
                        <div class="markdown-text">{{ r.content }}</div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>添加回复</span>
            </div>
            <div class='inner reply'>
                <form id='reply_form' action="{{ url_for('reply.add') }}" method='post'>
                    <div class='markdown_editor in_editor'>
                        <div class='markdown_in_editor'>
                            <input type="hidden" name="topic_id" value="{{ topic.id }}">
                            <textarea class='editor' name='content' rows='8'></textarea>
                            <div class='editor_buttons'>
                                <input class='span-primary submit_btn' type="submit" data-loading-text="回复中.." value="回复" >
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    var log = function() {
        console.log.apply(console, arguments)
    }

    var e = function(sel) {
        return document.querySelector(sel)
    }

    var es = function(sel) {
        return document.querySelectorAll(sel)
    }

    var registerTime = function() {
        var ctime = e('.col')
        var now = Math.floor(new Date() / 1000)
        var delta = Math.floor(((now - Number(ctime.id))/ 3600))
        var day = Math.floor(delta/24)
        var s = day
        ctime.innerText = s
    }

    var creatTime = function() {
        var ctimes = es('.last_active_time')
        for(var i = 0; i < ctimes.length; i++) {
            var now = Math.floor(new Date() / 1000)
            var delta = Math.floor(((now - Number(ctimes[i].id)) / 3600))
            var h = delta + '小时前'
            var d = Math.floor(delta/24)
            var dh = delta%24 + '小时前'
            if (d == 0) {
                ctimes[i].innerText = h
            } else {
                ctimes[i].innerText = d + '天'+dh
            }
        }
    }

    var markContents = function() {
        var contentDivs = es('.markdown-text')
        for(var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            var content = marked(contentDiv.innerHTML)
            // console.log(content, contentDiv.innerHTML)
            contentDiv.innerHTML = content
        }
    }

    var __main = function() {
        console.log('running')
        registerTime()
        creatTime()
        markContents()
    }

    __main()
</script>
{% endblock %}

templates/topic/index.html
{% extends "base.html" %}
{% block main %}
<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                {% if user.username == "admin" %}
                    <span class="col_fade">管理员信息</span>
                {% else %}
                    <span class="col_fade">个人信息</span>
                {% endif %}
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="{{ url_for('index.user_detail', username=user.username) }}">
                            <img src="{{ user.user_image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name"><a class="dark" href="{{ url_for('index.user_detail', username=user.username) }}">{{ user.username }}</a></span>
                        <div class="board clearfix"><div class="floor"></div></div>
                        <span class="signature">
                            {{ user.signature }}
                        </span>
                    </div>
                </div>
            </div>
        </div>

        {% if user.username == "admin" %}
        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('admin.index') }}" class="create_topic_btn">
                    <span class="span-info">用户管理</span>
                </a>
            </div>
        </div>
        {% endif %}

        <div class="panel">
            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>友情站点</span>
            </div>
            <div class='inner'>
                <ol class="friendship-community">
                    <li>
                        <a href="https://www.google.com/" target="_blank">
                            <img src="/static/image/google.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://github.com/" target="_blank">
                            <img src="/static/image/github1.jpg">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://www.zhihu.com/" target="_blank">
                            <img src="/static/image/zhihu.png">
                        </a>
                    </li>
                    <div class="sep10"></div>
                    <li>
                        <a href="https://stackoverflow.com/" target="_blank">
                            <img src="/static/image/stackoverflow1.jpg">
                        </a>
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ts %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="user_avatar" href="{{ url_for('index.user_detail', username=t.user().username) }}">
                                <img src="{{ t.user().user_image }}" title="{{ t.user().username }}">
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <a class='last_time pull-right' href="/">
                                <span class="last_active_time" id="{{ t.created_time }}"></span>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var log = function() {
        console.log.apply(console, arguments)
    }

    var e = function(sel) {
        return document.querySelector(sel)
    }

    var es = function(sel) {
        return document.querySelectorAll(sel)
    }

    var creatTime = function() {
        var ctimes = es('.last_active_time')
        for(var i = 0; i < ctimes.length; i++) {
            var now = Math.floor(new Date() / 1000)
            var delta = Math.floor(((now - Number(ctimes[i].id))/ 3600))

            var h = delta + '小时前'
            var d = Math.floor(delta/24)
            var dh = delta%24 + '小时前'
            if (d == 0) {
                ctimes[i].innerText = h
            } else {
                ctimes[i].innerText = d+'天'+dh
            }


        }
    }

    var __main = function() {
        console.log('running')
        creatTime()
    }

    __main()

    </script>
{% endblock %}

templates/topic/new.html
{% extends "base.html" %}
{% block main %}
    <div id="main">
        <div id='sidebar'>
            <div class='panel'>
                <div class='header'>
                    <span class='col_fade'>Markdown 语法参考</span>
                </div>
                <div class='inner'>
                    <ol>
                        <li><tt>### 单行的标题</tt></li>
                        <li><tt>**粗体**</tt></li>
                        <li><tt>`console.log('行内代码')`</tt></li>
                        <li><tt>```js\n code \n```</tt> 标记代码块</li>
                        <li><tt>[内容](链接)</tt></li>
                        <li><tt>![文字说明](图片链接)</tt></li>
                    </ol>
                    <span>
                        <a href='https://segmentfault.com/markdown' target='_blank'>Markdown 文档</a>
                    </span>
                </div>
            </div>

            <div class='panel'>
                <div class='header'>
                    <span class='col_fade'>话题发布指南</span>
                </div>
                <div class='inner'>
                    <ol>
                        <li>尽量把话题要点浓缩到标题里</li>
                        <li>
                            代码含义和报错可在
                            <a href="http://segmentfault.com/t/node.js">SegmentFault</a>
                            提问
                        </li>
                    </ol>
                </div>
            </div>
        </div>

        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <span class="tab-selector">选择版块：</span>
                            <select name="board_id" id="board" required>
                                {% for b in bs %}
                                    {% if bid == b.id %}
                                        <option value="{{ b.id }}" selected="selected" >{{ b.title }}</option>
                                    {% else %}
                                        <option value="{{ b.id }}" >{{ b.title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <div class='markdown_editor in_editor'>
                                <div class='markdown_in_editor'>

                                    <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                    <div class='editor_buttons'>
                                        <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                    </div>

                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
{% endblock %}